### PR TITLE
upgrade to cake 2.0.0

### PR DESCRIPTION
**Pull request by PEDK78**
upgrade to cake 2.0.0

### CODE REVIEW

**Comment by balage90** [comment]
Do you know guys when this can be released? thanks!

**Comment by fushinoryuu** [comment]
I would also love if this PR could be merged. Trying to upgrade to Cake 2.0 and can't, since I have a dependency on this package.

**Comment by domagojmedo** [comment]
@SharpeRAD can this be merged?

**Comment by petr-konopelko** [comment]
Dear, @SharpeRAD. I would also love to have it merged.
Thank you

**Comment by larsest1** [comment]
@SharpeRAD I also want to join the bunch of people who really would like this pr to be merged.

**Pull request merged**
