### PR TITLE
Update to Cake v1.0.0.

### PR DESCRIPTION
**Pull request by azchohfi**
Blocked by https://github.com/cake-contrib/Cake.FileHelpers/pull/34

### CODE REVIEW

**Comment by azchohfi** [comment]
Tests are failing on OSX and MacOS. Is this expected, given that linux support is partial?

**Comment by azchohfi** [comment]
I see what I did wrong. Fixing it.

**Comment by azchohfi** [comment]
Yes, results are not parsed on linux, so tests will fail.

**Comment by SharpeRAD** [comment]
Hey Alex, hope its ok to close this PR as #83 upticked to Cake v1.0.0 and added cross platform support

**Pull request closed without merging**
