### PR TITLE
Finish Cake 0.29 -> 0.33 transition

### LINKED ISSUE #75: The published 0.4.8 NuGet package hasn't got Cake.Core in dependencies
The 0.4.8 version depends on Cake.Core, but the dependency info is missing from nupkg

https://github.com/SharpeRAD/Cake.Powershell/commit/3bdbf955085eca8bddf0f74dbf1e258caeabde8b#diff-23506e4f03e24e1f1e6ef1d118c89178

### PR DESCRIPTION
**Pull request by marcinsmialek**
Resolves #75

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Why have you added a dependency on Cake.Core? Does Cake need a dependency to itself when loading an addin?

**Comment by marcinsmialek** [comment]
My point was that Cake.Powershell depends on and uses Cake.Core 0.33.
I wanted to show this explicitly by using NuGet dependencies, so it's not used with the legacy Cake version.

Assuming one always uses Cake 0.33, this change is of little value.

**Comment by SharpeRAD** [comment]
While I appreciate that Nuget spec recommends adding references to all dependencies, Cake does not. They even created a bot to [pick up on this](https://github.com/cake-contrib/Cake.AddinDiscoverer).

**Comment by marcinsmialek** [comment]
Thanks for clarification

**Pull request closed without merging**
